//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajdataEdit_Neo.Assets.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MajdataEdit_Neo.Assets.Langs.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Setting 的本地化字符串。
        /// </summary>
        internal static string Cat_EditSetting {
            get {
                return ResourceManager.GetString("Cat_EditSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Setting 的本地化字符串。
        /// </summary>
        internal static string Cat_ViewSetting {
            get {
                return ResourceManager.GetString("Cat_ViewSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Setting 的本地化字符串。
        /// </summary>
        internal static string Cat_VolumeSetting {
            get {
                return ResourceManager.GetString("Cat_VolumeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Gui_About {
            get {
                return ResourceManager.GetString("Gui_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;artist 的本地化字符串。
        /// </summary>
        internal static string Gui_Artist {
            get {
                return ResourceManager.GetString("Gui_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autosaves 的本地化字符串。
        /// </summary>
        internal static string Gui_AutoSaves {
            get {
                return ResourceManager.GetString("Gui_AutoSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beats 的本地化字符串。
        /// </summary>
        internal static string Gui_BeatsCount {
            get {
                return ResourceManager.GetString("Gui_BeatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BPM Tap 的本地化字符串。
        /// </summary>
        internal static string Gui_BpmTap {
            get {
                return ResourceManager.GetString("Gui_BpmTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart Info 的本地化字符串。
        /// </summary>
        internal static string Gui_ChartInfo {
            get {
                return ResourceManager.GetString("Gui_ChartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        internal static string Gui_CheckUpdate {
            get {
                return ResourceManager.GetString("Gui_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Commands 的本地化字符串。
        /// </summary>
        internal static string Gui_Commands {
            get {
                return ResourceManager.GetString("Gui_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress bg.mp4 的本地化字符串。
        /// </summary>
        internal static string Gui_CompressBgVideo {
            get {
                return ResourceManager.GetString("Gui_CompressBgVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Gui_Confirm {
            get {
                return ResourceManager.GetString("Gui_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        internal static string Gui_Connected {
            get {
                return ResourceManager.GetString("Gui_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Des 的本地化字符串。
        /// </summary>
        internal static string Gui_Designer {
            get {
                return ResourceManager.GetString("Gui_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty 的本地化字符串。
        /// </summary>
        internal static string Gui_Difficulty {
            get {
                return ResourceManager.GetString("Gui_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Gui_Edit {
            get {
                return ResourceManager.GetString("Gui_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Gui_Error {
            get {
                return ResourceManager.GetString("Gui_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Video From Here 的本地化字符串。
        /// </summary>
        internal static string Gui_ExportVideo {
            get {
                return ResourceManager.GetString("Gui_ExportVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string Gui_File {
            get {
                return ResourceManager.GetString("Gui_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;des 的本地化字符串。
        /// </summary>
        internal static string Gui_FinalDesigner {
            get {
                return ResourceManager.GetString("Gui_FinalDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find and Replace 的本地化字符串。
        /// </summary>
        internal static string Gui_FindAndReplace {
            get {
                return ResourceManager.GetString("Gui_FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Cursor 的本地化字符串。
        /// </summary>
        internal static string Gui_FollowCursor {
            get {
                return ResourceManager.GetString("Gui_FollowCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freeze First Frame 的本地化字符串。
        /// </summary>
        internal static string Gui_FreezeFrame {
            get {
                return ResourceManager.GetString("Gui_FreezeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global 的本地化字符串。
        /// </summary>
        internal static string Gui_Global {
            get {
                return ResourceManager.GetString("Gui_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Gui_Info {
            get {
                return ResourceManager.GetString("Gui_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        internal static string Gui_Level {
            get {
                return ResourceManager.GetString("Gui_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        internal static string Gui_Local {
            get {
                return ResourceManager.GetString("Gui_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Quick Process 的本地化字符串。
        /// </summary>
        internal static string Gui_MediaQuickProcess {
            get {
                return ResourceManager.GetString("Gui_MediaQuickProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust audio/video timing based on BPM and offset 的本地化字符串。
        /// </summary>
        internal static string Gui_MediaQuickProcessDesc {
            get {
                return ResourceManager.GetString("Gui_MediaQuickProcessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirror 180° 的本地化字符串。
        /// </summary>
        internal static string Gui_Mirror180 {
            get {
                return ResourceManager.GetString("Gui_Mirror180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirror Horizontally 的本地化字符串。
        /// </summary>
        internal static string Gui_MirrorHorizontally {
            get {
                return ResourceManager.GetString("Gui_MirrorHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirror Vertically 的本地化字符串。
        /// </summary>
        internal static string Gui_MirrorVertically {
            get {
                return ResourceManager.GetString("Gui_MirrorVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string Gui_New {
            get {
                return ResourceManager.GetString("Gui_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Chart From Video 的本地化字符串。
        /// </summary>
        internal static string Gui_NewChartFromVideo {
            get {
                return ResourceManager.GetString("Gui_NewChartFromVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset 的本地化字符串。
        /// </summary>
        internal static string Gui_Offset {
            get {
                return ResourceManager.GetString("Gui_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Gui_Open {
            get {
                return ResourceManager.GetString("Gui_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        internal static string Gui_PlaybackSpeed {
            get {
                return ResourceManager.GetString("Gui_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        internal static string Gui_Record {
            get {
                return ResourceManager.GetString("Gui_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recover 的本地化字符串。
        /// </summary>
        internal static string Gui_Recover {
            get {
                return ResourceManager.GetString("Gui_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Gui_Reset {
            get {
                return ResourceManager.GetString("Gui_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 45° 的本地化字符串。
        /// </summary>
        internal static string Gui_Rotate45 {
            get {
                return ResourceManager.GetString("Gui_Rotate45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate -45° 的本地化字符串。
        /// </summary>
        internal static string Gui_RotateNeg45 {
            get {
                return ResourceManager.GetString("Gui_RotateNeg45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Gui_Save {
            get {
                return ResourceManager.GetString("Gui_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Background Image 的本地化字符串。
        /// </summary>
        internal static string Gui_SelectBgImage {
            get {
                return ResourceManager.GetString("Gui_SelectBgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Background Video 的本地化字符串。
        /// </summary>
        internal static string Gui_SelectBgVideo {
            get {
                return ResourceManager.GetString("Gui_SelectBgVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Gui_Setting {
            get {
                return ResourceManager.GetString("Gui_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subdivide 1.5 Times 的本地化字符串。
        /// </summary>
        internal static string Gui_Subdivide1p5x {
            get {
                return ResourceManager.GetString("Gui_Subdivide1p5x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subdivide 2 Times 的本地化字符串。
        /// </summary>
        internal static string Gui_Subdivide2x {
            get {
                return ResourceManager.GetString("Gui_Subdivide2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Gui_Success {
            get {
                return ResourceManager.GetString("Gui_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap 的本地化字符串。
        /// </summary>
        internal static string Gui_Tap {
            get {
                return ResourceManager.GetString("Gui_Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;title 的本地化字符串。
        /// </summary>
        internal static string Gui_Title {
            get {
                return ResourceManager.GetString("Gui_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string Gui_Tools {
            get {
                return ResourceManager.GetString("Gui_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Gui_Warning {
            get {
                return ResourceManager.GetString("Gui_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close View? 的本地化字符串。
        /// </summary>
        internal static string Msg_AskCloseView {
            get {
                return ResourceManager.GetString("Msg_AskCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bg.mp4 is too large, Compress? 的本地化字符串。
        /// </summary>
        internal static string Msg_BgTooLarge {
            get {
                return ResourceManager.GetString("Msg_BgTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart not yet saved. Save it now? 的本地化字符串。
        /// </summary>
        internal static string Msg_ChartNotSaved {
            get {
                return ResourceManager.GetString("Msg_ChartNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to parse data, maybe you have checked update too many times 的本地化字符串。
        /// </summary>
        internal static string Msg_CheckUpdateParseFail {
            get {
                return ResourceManager.GetString("Msg_CheckUpdateParseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to fetch data, please check your internet connection. 的本地化字符串。
        /// </summary>
        internal static string Msg_CheckUpdateRequestFail {
            get {
                return ResourceManager.GetString("Msg_CheckUpdateRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can disable AutoCheckUpdate in &quot;Setting-&gt;Editor Setting&quot; 的本地化字符串。
        /// </summary>
        internal static string Msg_DisablingAutoCheckUpdate {
            get {
                return ResourceManager.GetString("Msg_DisablingAutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract failed: {0} 的本地化字符串。
        /// </summary>
        internal static string Msg_ExtractAudioFailed {
            get {
                return ResourceManager.GetString("Msg_ExtractAudioFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Beats Count! 的本地化字符串。
        /// </summary>
        internal static string Msg_InvalidBeatsCount {
            get {
                return ResourceManager.GetString("Msg_InvalidBeatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maidata Already Exist 的本地化字符串。
        /// </summary>
        internal static string Msg_MaidataAlreadyExist {
            get {
                return ResourceManager.GetString("Msg_MaidataAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media processing complete 的本地化字符串。
        /// </summary>
        internal static string Msg_MediaProcessComplete {
            get {
                return ResourceManager.GetString("Msg_MediaProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust failed: {0} 的本地化字符串。
        /// </summary>
        internal static string Msg_MediaProcessFailed {
            get {
                return ResourceManager.GetString("Msg_MediaProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Version detected: {0}
        ///(Current Version: {1})
        ///
        ///Do you want to download the latest update of Majdata? 的本地化字符串。
        /// </summary>
        internal static string Msg_NewVersionDetected {
            get {
                return ResourceManager.GetString("Msg_NewVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No autosave files are available. 的本地化字符串。
        /// </summary>
        internal static string Msg_NoAutoSaveFound {
            get {
                return ResourceManager.GetString("Msg_NoAutoSaveFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter &apos;(BPM){1},&apos; in the chart first! 的本地化字符串。
        /// </summary>
        internal static string Msg_NoBpmInChart {
            get {
                return ResourceManager.GetString("Msg_NoBpmInChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already at the latest version 的本地化字符串。
        /// </summary>
        internal static string Msg_NoNewVersion {
            get {
                return ResourceManager.GetString("Msg_NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to recover the autosave file. 的本地化字符串。
        /// </summary>
        internal static string Msg_RecoverFailed {
            get {
                return ResourceManager.GetString("Msg_RecoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Answer 的本地化字符串。
        /// </summary>
        internal static string Set_Answer {
            get {
                return ResourceManager.GetString("Set_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Check Updates On Startup 的本地化字符串。
        /// </summary>
        internal static string Set_AutoCheckUpdatesOnStartup {
            get {
                return ResourceManager.GetString("Set_AutoCheckUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Mode 的本地化字符串。
        /// </summary>
        internal static string Set_AutoMode {
            get {
                return ResourceManager.GetString("Set_AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Dim 的本地化字符串。
        /// </summary>
        internal static string Set_BackgroundDim {
            get {
                return ResourceManager.GetString("Set_BackgroundDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor Background Image 的本地化字符串。
        /// </summary>
        internal static string Set_BackgroundImagePath {
            get {
                return ResourceManager.GetString("Set_BackgroundImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outside Background Dim 的本地化字符串。
        /// </summary>
        internal static string Set_BackgroundOutsideDim {
            get {
                return ResourceManager.GetString("Set_BackgroundOutsideDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break 的本地化字符串。
        /// </summary>
        internal static string Set_Break {
            get {
                return ResourceManager.GetString("Set_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DJAuto Button First 的本地化字符串。
        /// </summary>
        internal static string Set_ButtonFirst {
            get {
                return ResourceManager.GetString("Set_ButtonFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combo Status Type 的本地化字符串。
        /// </summary>
        internal static string Set_ComboStatusType {
            get {
                return ResourceManager.GetString("Set_ComboStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Quality 的本地化字符串。
        /// </summary>
        internal static string Set_ExportQuality {
            get {
                return ResourceManager.GetString("Set_ExportQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size 的本地化字符串。
        /// </summary>
        internal static string Set_FontSize {
            get {
                return ResourceManager.GetString("Set_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Audio Offset 的本地化字符串。
        /// </summary>
        internal static string Set_GlobalAudioOffset {
            get {
                return ResourceManager.GetString("Set_GlobalAudioOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Judge Display Mode 的本地化字符串。
        /// </summary>
        internal static string Set_JudgeDisplayMode {
            get {
                return ResourceManager.GetString("Set_JudgeDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Set_Language {
            get {
                return ResourceManager.GetString("Set_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legacy Slide Layer 的本地化字符串。
        /// </summary>
        internal static string Set_LegacySlideLayer {
            get {
                return ResourceManager.GetString("Set_LegacySlideLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mine Slide Autoplay 的本地化字符串。
        /// </summary>
        internal static string Set_MineAutoSlide {
            get {
                return ResourceManager.GetString("Set_MineAutoSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output FPS 的本地化字符串。
        /// </summary>
        internal static string Set_OutputFps {
            get {
                return ResourceManager.GetString("Set_OutputFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FullScreen BG 的本地化字符串。
        /// </summary>
        internal static string Set_ResizeBg {
            get {
                return ResourceManager.GetString("Set_ResizeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Autoplay&apos;s Hand 的本地化字符串。
        /// </summary>
        internal static string Set_ShowHand {
            get {
                return ResourceManager.GetString("Set_ShowHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide 的本地化字符串。
        /// </summary>
        internal static string Set_Slide {
            get {
                return ResourceManager.GetString("Set_Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth Slide Animation 的本地化字符串。
        /// </summary>
        internal static string Set_SmoothSlideAnime {
            get {
                return ResourceManager.GetString("Set_SmoothSlideAnime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap 的本地化字符串。
        /// </summary>
        internal static string Set_Tap {
            get {
                return ResourceManager.GetString("Set_Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap Speed 的本地化字符串。
        /// </summary>
        internal static string Set_TapSpeed {
            get {
                return ResourceManager.GetString("Set_TapSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touch 的本地化字符串。
        /// </summary>
        internal static string Set_Touch {
            get {
                return ResourceManager.GetString("Set_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touch Speed 的本地化字符串。
        /// </summary>
        internal static string Set_TouchSpeed {
            get {
                return ResourceManager.GetString("Set_TouchSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track 的本地化字符串。
        /// </summary>
        internal static string Set_Track {
            get {
                return ResourceManager.GetString("Set_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Type 的本地化字符串。
        /// </summary>
        internal static string Set_UIType {
            get {
                return ResourceManager.GetString("Set_UIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wave Animate 的本地化字符串。
        /// </summary>
        internal static string Set_WaveAnimated {
            get {
                return ResourceManager.GetString("Set_WaveAnimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Wrap 的本地化字符串。
        /// </summary>
        internal static string Set_WordWrap {
            get {
                return ResourceManager.GetString("Set_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Busy 的本地化字符串。
        /// </summary>
        internal static string Status_Busy {
            get {
                return ResourceManager.GetString("Status_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video compression complete 的本地化字符串。
        /// </summary>
        internal static string Status_CompressComplete {
            get {
                return ResourceManager.GetString("Status_CompressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video compression failed 的本地化字符串。
        /// </summary>
        internal static string Status_CompressFailed {
            get {
                return ResourceManager.GetString("Status_CompressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressing video... (Press Esc to cancel) 的本地化字符串。
        /// </summary>
        internal static string Status_Compressing {
            get {
                return ResourceManager.GetString("Status_Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        internal static string Status_Disconnected {
            get {
                return ResourceManager.GetString("Status_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting audio... (Press Esc to cancel) 的本地化字符串。
        /// </summary>
        internal static string Status_ExtractingAudio {
            get {
                return ResourceManager.GetString("Status_ExtractingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        internal static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded 的本地化字符串。
        /// </summary>
        internal static string Status_Loaded {
            get {
                return ResourceManager.GetString("Status_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No bg.mp4/pv.mp4 found 的本地化字符串。
        /// </summary>
        internal static string Status_NoBgVideo {
            get {
                return ResourceManager.GetString("Status_NoBgVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A compatible FFmpeg installation was not found. 的本地化字符串。
        /// </summary>
        internal static string Status_NoFfmpeg {
            get {
                return ResourceManager.GetString("Status_NoFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        internal static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playing 的本地化字符串。
        /// </summary>
        internal static string Status_Playing {
            get {
                return ResourceManager.GetString("Status_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing media... 的本地化字符串。
        /// </summary>
        internal static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BPM Tap 的本地化字符串。
        /// </summary>
        internal static string Win_BpmTap {
            get {
                return ResourceManager.GetString("Win_BpmTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart Info 的本地化字符串。
        /// </summary>
        internal static string Win_ChartInfo {
            get {
                return ResourceManager.GetString("Win_ChartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autosave Recover 的本地化字符串。
        /// </summary>
        internal static string Win_Recover {
            get {
                return ResourceManager.GetString("Win_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Win_Settings {
            get {
                return ResourceManager.GetString("Win_Settings", resourceCulture);
            }
        }
    }
}
